spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory
    username: root
    password: r0otH@mza
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

mailgun:
  domain: ${MAILGUN_DOMAIN}
  from-email: ${MAILGUN_FROM_EMAIL}
  username: ${MAILGUN_USERNAME}
  password: ${MAILGUN_PASSWORD}